--liquibase formatted sql

--changeset peakda:20260513-004-create-weather-mid-forecasts
CREATE TABLE weather_mid_forecasts (
    id                          BIGSERIAL   PRIMARY KEY,
    region_code                 TEXT        NOT NULL,
    announce_time               TEXT        NOT NULL,
    weather_day3_am             TEXT,
    weather_day3_pm             TEXT,
    weather_day4_am             TEXT,
    weather_day4_pm             TEXT,
    weather_day5_am             TEXT,
    weather_day5_pm             TEXT,
    weather_day6_am             TEXT,
    weather_day6_pm             TEXT,
    weather_day7_am             TEXT,
    weather_day7_pm             TEXT,
    weather_day8                TEXT,
    weather_day9                TEXT,
    weather_day10               TEXT,
    rain_probability_day3_am    INTEGER,
    rain_probability_day3_pm    INTEGER,
    rain_probability_day4_am    INTEGER,
    rain_probability_day4_pm    INTEGER,
    rain_probability_day5_am    INTEGER,
    rain_probability_day5_pm    INTEGER,
    rain_probability_day6_am    INTEGER,
    rain_probability_day6_pm    INTEGER,
    rain_probability_day7_am    INTEGER,
    rain_probability_day7_pm    INTEGER,
    rain_probability_day8       INTEGER,
    rain_probability_day9       INTEGER,
    rain_probability_day10      INTEGER,
    temperature_min_day3        INTEGER,
    temperature_max_day3        INTEGER,
    temperature_min_day4        INTEGER,
    temperature_max_day4        INTEGER,
    temperature_min_day5        INTEGER,
    temperature_max_day5        INTEGER,
    temperature_min_day6        INTEGER,
    temperature_max_day6        INTEGER,
    temperature_min_day7        INTEGER,
    temperature_max_day7        INTEGER,
    temperature_min_day8        INTEGER,
    temperature_max_day8        INTEGER,
    temperature_min_day9        INTEGER,
    temperature_max_day9        INTEGER,
    temperature_min_day10       INTEGER,
    temperature_max_day10       INTEGER,
    created_at                  TIMESTAMPTZ NOT NULL,
    updated_at                  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_weather_mid_forecasts_region_announce UNIQUE (region_code, announce_time)
);

CREATE INDEX idx_weather_mid_forecasts_announce_time ON weather_mid_forecasts (announce_time DESC);
--rollback DROP TABLE weather_mid_forecasts;
