--liquibase formatted sql

--changeset peakda:20260513-004-create-weather-mid-forecasts
CREATE TABLE weather_mid_forecasts (
    id          BIGSERIAL   PRIMARY KEY,
    reg_id      TEXT        NOT NULL,
    tm_fc       TEXT        NOT NULL,
    wf3_am      TEXT,
    wf3_pm      TEXT,
    wf4_am      TEXT,
    wf4_pm      TEXT,
    wf5_am      TEXT,
    wf5_pm      TEXT,
    wf6_am      TEXT,
    wf6_pm      TEXT,
    wf7_am      TEXT,
    wf7_pm      TEXT,
    wf8         TEXT,
    wf9         TEXT,
    wf10        TEXT,
    rn_st3_am   INTEGER,
    rn_st3_pm   INTEGER,
    rn_st4_am   INTEGER,
    rn_st4_pm   INTEGER,
    rn_st5_am   INTEGER,
    rn_st5_pm   INTEGER,
    rn_st6_am   INTEGER,
    rn_st6_pm   INTEGER,
    rn_st7_am   INTEGER,
    rn_st7_pm   INTEGER,
    rn_st8      INTEGER,
    rn_st9      INTEGER,
    rn_st10     INTEGER,
    ta_min3     INTEGER,
    ta_max3     INTEGER,
    ta_min4     INTEGER,
    ta_max4     INTEGER,
    ta_min5     INTEGER,
    ta_max5     INTEGER,
    ta_min6     INTEGER,
    ta_max6     INTEGER,
    ta_min7     INTEGER,
    ta_max7     INTEGER,
    ta_min8     INTEGER,
    ta_max8     INTEGER,
    ta_min9     INTEGER,
    ta_max9     INTEGER,
    ta_min10    INTEGER,
    ta_max10    INTEGER,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_weather_mid_forecasts_reg_tmfc UNIQUE (reg_id, tm_fc)
);

CREATE INDEX idx_weather_mid_forecasts_tm_fc ON weather_mid_forecasts (tm_fc DESC);
--rollback DROP TABLE weather_mid_forecasts;
