package com.peakda.server.domain.admin.entity

enum class AdminAuditAction {
    REPORT_RESOLVE_HIDE,
    REPORT_RESOLVE_KEEP,
    REPORT_DISMISS,
    SPOT_RECORD_HIDE,
    SPOT_RECORD_RESTORE,
    PLANT_UPDATE,
    PLANT_REJECT,
    PLANT_RESTORE,
    CURATION_UPSERT,
    CURATION_DELETE,
    FESTIVAL_EDITORIAL_UPSERT,
    FESTIVAL_EDITORIAL_DELETE,
    NOTICE_CREATE,
    NOTICE_UPDATE,
    NOTICE_DISPATCH,
    NOTICE_CANCEL,
    USER_SUSPEND,
    USER_UNSUSPEND,
    SCHEDULER_JOB_TRIGGER,
}
